version: "3.9"

services:
  dxvk-cache-bank:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  # This service will be used in the future
  postgresql:
    image: postgres:14.3-alpine3.16
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=dxvk-cache-bank-db