create table cache_file (
    id int8 generated by default as identity,
    data oid,
    upload_date timestamp not null,
    game_id int8 not null,
    "uploader_id" int8,
    primary key (id)
);

create table game (
    id int8 generated by default as identity,
    cache_file_name varchar(255) not null,
    incremental_cache_file oid,
    incremental_cache_last_modified timestamp,
    name varchar(255) not null,
    steam_id int8,
    primary key (id)
);

create table "user" (
    id int8 generated by default as identity,
    email varchar(255) not null,
    name varchar(255) not null,
    password varchar(255) not null,
    profile_picture oid,
    primary key (id)
);

alter table if exists game add constraint UK_jare70vqqti665ds3b2eh7rk8 unique (name);

alter table if exists game add constraint UK_52c8vf454pk3kmfv349xh5en5 unique (steam_id);

alter table if exists "user" add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);

alter table if exists "user" add constraint UK_gj2fy3dcix7ph7k8684gka40c unique (name);

alter table if exists cache_file add constraint game_id foreign key (game_id) references game;

alter table if exists cache_file add constraint uploader_id foreign key ("uploader_id") references "user";